/*
 * App Nizi API
 *
 * The API for the Nizi-app
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;
using IO.Swagger.Security;
using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class DietaryManagementApiController : ControllerBase
    { 
        /// <summary>
        /// Deletes the diatarymanagement of a patient
        /// </summary>
        /// <remarks>Deletes the dietarymanagement of a patient.</remarks>
        /// <param name="dietId">the id of the diet</param>
        /// <response code="200">OK</response>
        /// <response code="401">you are unauthorized to do this</response>
        [HttpDelete]
        [Route("/McSmoker/NierZiektenConcept/1.0.0//personaldietarymanagement/{DietId}")]
        [ValidateModelState]
        [SwaggerOperation("DeleteMyDietaryManagement")]
        public virtual IActionResult DeleteMyDietaryManagement([FromRoute][Required]int? dietId)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            //TODO: Uncomment the next line to return response 401 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(401);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Returns all nutrients of a patient
        /// </summary>
        /// <remarks>Retrieves all dietarymanagment of the patient.</remarks>
        /// <param name="patientId">The id of the patient</param>
        /// <response code="200">OK</response>
        /// <response code="401">you are unauthorized to see these patients dietary manegment</response>
        /// <response code="403">this is not your dietary management</response>
        /// <response code="404">this patient is not found</response>
        [HttpGet]
        [Route("/McSmoker/NierZiektenConcept/1.0.0//dietaryManagement/{patientId}")]
        [ValidateModelState]
        [SwaggerOperation("GetAllDietaryManagementForPatient")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<Nutrient>), description: "OK")]
        public virtual IActionResult GetAllDietaryManagementForPatient([FromRoute][Required]int? patientId)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(List<Nutrient>));

            //TODO: Uncomment the next line to return response 401 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(401);

            //TODO: Uncomment the next line to return response 403 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(403);

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404);
            string exampleJson = null;
            exampleJson = "[ {\n  \"Active\" : true,\n  \"Amount\" : 0,\n  \"Name\" : \"Name\"\n}, {\n  \"Active\" : true,\n  \"Amount\" : 0,\n  \"Name\" : \"Name\"\n} ]";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<List<Nutrient>>(exampleJson)
                        : default(List<Nutrient>);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// Edits the dietarymanagement of a patient
        /// </summary>
        /// <remarks>Edits the dietarymanagement of a patient.</remarks>
        /// <param name="body">the diet management that needs to be updated</param>
        /// <response code="200">OK</response>
        /// <response code="401">you are unauthorized to do this</response>
        /// <response code="404">this patient is not found</response>
        [HttpPut]
        [Route("/McSmoker/NierZiektenConcept/1.0.0//dietaryManagement")]
        [ValidateModelState]
        [SwaggerOperation("PutDietaryManagement")]
        public virtual IActionResult PutDietaryManagement([FromBody]UpdatedDietmangement body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            //TODO: Uncomment the next line to return response 401 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(401);

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404);

            throw new NotImplementedException();
        }
    }
}
