/*
 * App Nizi API
 *
 * The API for the Nizi-app
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;
using IO.Swagger.Security;
using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class WaterConsumptionApiController : ControllerBase
    { 
        /// <summary>
        /// Returns the waterconsumption of a patient
        /// </summary>
        /// <remarks>get the WaterConsumption of a patient.</remarks>
        /// <param name="patientId">The id of the patient</param>
        /// <response code="200">OK</response>
        /// <response code="401">you are unauthorized to do this</response>
        [HttpGet]
        [Route("/McSmoker/NierZiektenConcept/1.0.0//WaterConsumption/{patientId}")]
        [ValidateModelState]
        [SwaggerOperation("GetWaterConsumptionByPatientId")]
        public virtual IActionResult GetWaterConsumptionByPatientId([FromRoute][Required]int? patientId)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            //TODO: Uncomment the next line to return response 401 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(401);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Inserts the waterconsumption
        /// </summary>
        /// <remarks>Insert the WaterConsumption.</remarks>
        /// <param name="body">the water consumption of that day</param>
        /// <response code="200">OK</response>
        /// <response code="401">you are unauthorized to do this</response>
        [HttpPost]
        [Route("/McSmoker/NierZiektenConcept/1.0.0//waterConsumption")]
        [ValidateModelState]
        [SwaggerOperation("PostWaterConsumption")]
        public virtual IActionResult PostWaterConsumption([FromBody]WaterConsumption body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            //TODO: Uncomment the next line to return response 401 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(401);

            throw new NotImplementedException();
        }
    }
}
