/*
 * App Nizi API
 *
 * The API for the Nizi-app
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class FoodInner : IEquatable<FoodInner>
    { 
        /// <summary>
        /// Gets or Sets FoodId
        /// </summary>
        [DataMember(Name="foodId")]
        public int? FoodId { get; set; }

        /// <summary>
        /// Gets or Sets FoodName
        /// </summary>
        [DataMember(Name="foodName")]
        public string FoodName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FoodInner {\n");
            sb.Append("  FoodId: ").Append(FoodId).Append("\n");
            sb.Append("  FoodName: ").Append(FoodName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((FoodInner)obj);
        }

        /// <summary>
        /// Returns true if FoodInner instances are equal
        /// </summary>
        /// <param name="other">Instance of FoodInner to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FoodInner other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    FoodId == other.FoodId ||
                    FoodId != null &&
                    FoodId.Equals(other.FoodId)
                ) && 
                (
                    FoodName == other.FoodName ||
                    FoodName != null &&
                    FoodName.Equals(other.FoodName)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (FoodId != null)
                    hashCode = hashCode * 59 + FoodId.GetHashCode();
                    if (FoodName != null)
                    hashCode = hashCode * 59 + FoodName.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(FoodInner left, FoodInner right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(FoodInner left, FoodInner right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
